name = "plume"
version = "1.0.0"
gleam = ">= 1.16.0"
description = "Sensible HTTP security headers for Gleam web servers, inspired by helmet."
licences = ["MIT"]
repository = { type = "github", user = "scott-ray-wilson", repo = "plume" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
